apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
      - infra/k8s-dev/*
build:
  local:
    push: false # don't push to dockerhub
  artifacts: # clarify of deployment
    - image: willnguyen/auth-service
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync: # listen for files changes and deploy to dest which is in container
        manual:
          - src: 'src/**/*.ts'
            dest: .

# build, listen, build...
