apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-ui-depl
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-ui
  template:
    metadata:
      labels:
        app: grafana-ui
    spec:
      containers:
        - name: grafana-ui
          image: grafana/grafana:latest

          
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-ui-srv
  namespace: monitoring
spec:
  selector:
    app: grafana-ui
  ports:
    - name: db
      protocol: TCP
      port: 3000
      targetPort: 3000

